config/routes.rb
Rails.application.routes.draw do
  resources :paticipants
  resources :events

end

app/models/event.rb
class Event < ActiveRecord::Base
	validates :name, presence: true

	has_many :participants
end

app/models/paticipant.rb
class Paticipant < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :description, :event_date)
    end
end

app/controllers/paticipants_controller.rb
class PaticipantsController < ApplicationController
  before_action :set_paticipant, only: [:show, :edit, :update, :destroy]

  # GET /paticipants
  # GET /paticipants.json
  def index
    @paticipants = Paticipant.all
  end

  # GET /paticipants/1
  # GET /paticipants/1.json
  def show
  end

  # GET /paticipants/new
  def new
    @paticipant = Paticipant.new
  end

  # GET /paticipants/1/edit
  def edit
  end

  # POST /paticipants
  # POST /paticipants.json
  def create
    @paticipant = Paticipant.new(paticipant_params)

    respond_to do |format|
      if @paticipant.save
        format.html { redirect_to @paticipant, notice: 'Paticipant was successfully created.' }
        format.json { render :show, status: :created, location: @paticipant }
      else
        format.html { render :new }
        format.json { render json: @paticipant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /paticipants/1
  # PATCH/PUT /paticipants/1.json
  def update
    respond_to do |format|
      if @paticipant.update(paticipant_params)
        format.html { redirect_to @paticipant, notice: 'Paticipant was successfully updated.' }
        format.json { render :show, status: :ok, location: @paticipant }
      else
        format.html { render :edit }
        format.json { render json: @paticipant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paticipants/1
  # DELETE /paticipants/1.json
  def destroy
    @paticipant.destroy
    respond_to do |format|
      format.html { redirect_to paticipants_url, notice: 'Paticipant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paticipant
      @paticipant = Paticipant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def paticipant_params
      params.require(:paticipant).permit(:name, :event_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/paticipants_helper.rb
module PaticipantsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :event_date %><br>
    <%= f.datetime_select :event_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Events</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Event date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.description %></td>
        <td><%= event.event_date %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Event date:</strong>
  <%= @event.event_date %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OpensancaMeeting</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/paticipants/_form.html.erb
<%= simple_form_for(@paticipant) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :event_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/paticipants/edit.html.erb
<h1>Editing Paticipant</h1>

<%= render 'form' %>

<%= link_to 'Show', @paticipant %> |
<%= link_to 'Back', paticipants_path %>

app/views/paticipants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Paticipants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Event</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @paticipants.each do |paticipant| %>
      <tr>
        <td><%= paticipant.name %></td>
        <td><%= paticipant.event_id %></td>
        <td><%= link_to 'Show', paticipant %></td>
        <td><%= link_to 'Edit', edit_paticipant_path(paticipant) %></td>
        <td><%= link_to 'Destroy', paticipant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Paticipant', new_paticipant_path %>

app/views/paticipants/new.html.erb
<h1>New Paticipant</h1>

<%= render 'form' %>

<%= link_to 'Back', paticipants_path %>

app/views/paticipants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @paticipant.name %>
</p>

<p>
  <strong>Event:</strong>
  <%= @paticipant.event_id %>
</p>

<%= link_to 'Edit', edit_paticipant_path(@paticipant) %> |
<%= link_to 'Back', paticipants_path %>